import { test, expect } from '@playwright/test';

test('add recipe', async ({ page }) => {
    await page.goto('http://localhost:4200/');
    await page.getByLabel('Recipe title').click();
    await page.getByLabel('Recipe title').fill('Pulav');
    await page.getByLabel('Recipe description').click();
    await page.getByLabel('Recipe description').fill('A delicious and nutritious stir-fry recipe with tofu and assorted vegetables.');
    await page.getByLabel('Instruction').click();
    await page.getByLabel('Instruction').fill('Heat sesame oil in a wok over medium-high heat.');
    await page.getByRole('button', { name: 'Add Instruction' }).click();
    await page.getByLabel('Instruction 2').click();
    await page.getByLabel('Instruction 2').fill('Add cubed tofu and stir-fry until golden brown.');
    await page.getByRole('button', { name: 'Add Instruction' }).click();
    await page.getByLabel('Instruction 3').click();
    await page.getByLabel('Instruction 3').fill('Add sliced bell peppers, broccoli florets, and snap peas.');
    await page.getByLabel('Ingredient Name').click();
    await page.getByLabel('Ingredient Name').fill('Firm tofu');
    await page.getByLabel('Quantity').click();
    await page.getByLabel('Quantity').fill('400g');
    await page.getByRole('button', { name: 'Add Ingredient' }).click();
    await page.getByLabel('Ingredient Name').nth(1).click();
    await page.getByLabel('Ingredient Name').nth(1).fill('Broccoli florets');
    await page.getByLabel('Quantity').nth(1).click();
    await page.getByLabel('Quantity').nth(1).fill('1 cup');
    await page.getByLabel('Calories').click();
    await page.getByLabel('Calories').fill('100');
    await page.getByLabel('Fats').click();
    await page.getByLabel('Fats').fill('25');
    await page.getByLabel('Carbs').click();
    await page.getByLabel('Carbs').fill('20');
    await page.getByLabel('Proteins').click();
    await page.getByLabel('Proteins').fill('20');
    await page.getByRole('button', { name: 'Submit' }).click();
  });